// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package poc.protobuf.protos;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poc_protobuf_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poc_protobuf_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poc_protobuf_Person_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poc_protobuf_Person_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poc_protobuf_AddressBook_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poc_protobuf_AddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021addressbook.proto\022\014poc.protobuf\"\343\001\n\006Pe" +
      "rson\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005email\030" +
      "\003 \001(\t\0220\n\006phones\030\004 \003(\0132 .poc.protobuf.Per" +
      "son.PhoneNumber\032Q\n\013PhoneNumber\022\016\n\006number" +
      "\030\001 \001(\t\0222\n\004type\030\002 \001(\0162\036.poc.protobuf.Pers" +
      "on.PhoneType:\004HOME\"+\n\tPhoneType\022\n\n\006MOBIL" +
      "E\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002\"3\n\013AddressBook\022$" +
      "\n\006people\030\001 \003(\0132\024.poc.protobuf.PersonB*\n\023" +
      "poc.protobuf.protosB\021AddressBookProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_poc_protobuf_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_poc_protobuf_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poc_protobuf_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Phones", });
    internal_static_poc_protobuf_Person_PhoneNumber_descriptor =
      internal_static_poc_protobuf_Person_descriptor.getNestedTypes().get(0);
    internal_static_poc_protobuf_Person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poc_protobuf_Person_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_poc_protobuf_AddressBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_poc_protobuf_AddressBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poc_protobuf_AddressBook_descriptor,
        new java.lang.String[] { "People", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
