// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package poc.protobuf.protos;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:poc.protobuf.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .poc.protobuf.Person people = 1;</code>
   */
  java.util.List<poc.protobuf.protos.Person> 
      getPeopleList();
  /**
   * <code>repeated .poc.protobuf.Person people = 1;</code>
   */
  poc.protobuf.protos.Person getPeople(int index);
  /**
   * <code>repeated .poc.protobuf.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .poc.protobuf.Person people = 1;</code>
   */
  java.util.List<? extends poc.protobuf.protos.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .poc.protobuf.Person people = 1;</code>
   */
  poc.protobuf.protos.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
