// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderinvoice.proto

package poc.protobuf.protos;

public final class OrderInvoiceProtos {
  private OrderInvoiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poc_protobuf_OrderInvoice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poc_protobuf_OrderInvoice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022orderinvoice.proto\022\014poc.protobuf\"\374\001\n\014O" +
      "rderInvoice\022\017\n\007orderId\030\001 \001(\005\0227\n\torderTyp" +
      "e\030\002 \001(\0162$.poc.protobuf.OrderInvoice.Orde" +
      "rType\022\022\n\ncustomerId\030\003 \001(\005\022\021\n\tproductId\030\004" +
      " \001(\005\022\020\n\010quantity\030\005 \001(\005\022\021\n\tinvoiceId\030\006 \001(" +
      "\005\022#\n\033invoiceAmountInRoundDollars\030\007 \001(\005\"1" +
      "\n\tOrderType\022\n\n\006DIRECT\020\000\022\n\n\006PICKUP\020\001\022\014\n\010D" +
      "ELIVERY\020\002B+\n\023poc.protobuf.protosB\022OrderI" +
      "nvoiceProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_poc_protobuf_OrderInvoice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_poc_protobuf_OrderInvoice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poc_protobuf_OrderInvoice_descriptor,
        new java.lang.String[] { "OrderId", "OrderType", "CustomerId", "ProductId", "Quantity", "InvoiceId", "InvoiceAmountInRoundDollars", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
