// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderstatus.proto

package poc.protobuf.protos;

public final class OrderStatusUpdateProtos {
  private OrderStatusUpdateProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poc_protobuf_OrderStatusUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poc_protobuf_OrderStatusUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021orderstatus.proto\022\014poc.protobuf\"\345\001\n\021Or" +
      "derStatusUpdate\022\017\n\007orderId\030\001 \001(\005\022@\n\013orde" +
      "rStatus\030\002 \001(\0162+.poc.protobuf.OrderStatus" +
      "Update.OrderStatus\"}\n\013OrderStatus\022\022\n\016ORD" +
      "ER_RECEIVED\020\000\022\016\n\nPROCESSING\020\001\022\013\n\007SHIPPED" +
      "\020\002\022\r\n\tDELIVERED\020\003\022\024\n\020READY_FOR_PICKUP\020\004\022" +
      "\030\n\024CUST_PICKUP_COMPLETE\020\005B0\n\023poc.protobu" +
      "f.protosB\027OrderStatusUpdateProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_poc_protobuf_OrderStatusUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_poc_protobuf_OrderStatusUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poc_protobuf_OrderStatusUpdate_descriptor,
        new java.lang.String[] { "OrderId", "OrderStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
