// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderinvoice.proto

package poc.protobuf.protos;

public interface OrderInvoiceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:poc.protobuf.OrderInvoice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 orderId = 1;</code>
   * @return Whether the orderId field is set.
   */
  boolean hasOrderId();
  /**
   * <code>optional int32 orderId = 1;</code>
   * @return The orderId.
   */
  int getOrderId();

  /**
   * <code>optional .poc.protobuf.OrderInvoice.OrderType orderType = 2;</code>
   * @return Whether the orderType field is set.
   */
  boolean hasOrderType();
  /**
   * <code>optional .poc.protobuf.OrderInvoice.OrderType orderType = 2;</code>
   * @return The orderType.
   */
  poc.protobuf.protos.OrderInvoice.OrderType getOrderType();

  /**
   * <code>optional int32 customerId = 3;</code>
   * @return Whether the customerId field is set.
   */
  boolean hasCustomerId();
  /**
   * <code>optional int32 customerId = 3;</code>
   * @return The customerId.
   */
  int getCustomerId();

  /**
   * <code>optional int32 productId = 4;</code>
   * @return Whether the productId field is set.
   */
  boolean hasProductId();
  /**
   * <code>optional int32 productId = 4;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>optional int32 quantity = 5;</code>
   * @return Whether the quantity field is set.
   */
  boolean hasQuantity();
  /**
   * <code>optional int32 quantity = 5;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>optional int32 invoiceId = 6;</code>
   * @return Whether the invoiceId field is set.
   */
  boolean hasInvoiceId();
  /**
   * <code>optional int32 invoiceId = 6;</code>
   * @return The invoiceId.
   */
  int getInvoiceId();

  /**
   * <code>optional int32 invoiceAmountInRoundDollars = 7;</code>
   * @return Whether the invoiceAmountInRoundDollars field is set.
   */
  boolean hasInvoiceAmountInRoundDollars();
  /**
   * <code>optional int32 invoiceAmountInRoundDollars = 7;</code>
   * @return The invoiceAmountInRoundDollars.
   */
  int getInvoiceAmountInRoundDollars();
}
