// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ordercreated.proto

package poc.protobuf.protos;

/**
 * Protobuf type {@code poc.protobuf.OrderCreated}
 */
public final class OrderCreated extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:poc.protobuf.OrderCreated)
    OrderCreatedOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderCreated.newBuilder() to construct.
  private OrderCreated(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderCreated() {
    orderType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OrderCreated();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return poc.protobuf.protos.OrderCreatedProtos.internal_static_poc_protobuf_OrderCreated_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return poc.protobuf.protos.OrderCreatedProtos.internal_static_poc_protobuf_OrderCreated_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            poc.protobuf.protos.OrderCreated.class, poc.protobuf.protos.OrderCreated.Builder.class);
  }

  /**
   * Protobuf enum {@code poc.protobuf.OrderCreated.OrderType}
   */
  public enum OrderType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DIRECT = 0;</code>
     */
    DIRECT(0),
    /**
     * <code>PICKUP = 1;</code>
     */
    PICKUP(1),
    /**
     * <code>DELIVERY = 2;</code>
     */
    DELIVERY(2),
    ;

    /**
     * <code>DIRECT = 0;</code>
     */
    public static final int DIRECT_VALUE = 0;
    /**
     * <code>PICKUP = 1;</code>
     */
    public static final int PICKUP_VALUE = 1;
    /**
     * <code>DELIVERY = 2;</code>
     */
    public static final int DELIVERY_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OrderType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OrderType forNumber(int value) {
      switch (value) {
        case 0: return DIRECT;
        case 1: return PICKUP;
        case 2: return DELIVERY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OrderType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OrderType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OrderType>() {
            public OrderType findValueByNumber(int number) {
              return OrderType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return poc.protobuf.protos.OrderCreated.getDescriptor().getEnumTypes().get(0);
    }

    private static final OrderType[] VALUES = values();

    public static OrderType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OrderType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:poc.protobuf.OrderCreated.OrderType)
  }

  private int bitField0_;
  public static final int ORDERID_FIELD_NUMBER = 1;
  private int orderId_;
  /**
   * <code>optional int32 orderId = 1;</code>
   * @return Whether the orderId field is set.
   */
  @java.lang.Override
  public boolean hasOrderId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 orderId = 1;</code>
   * @return The orderId.
   */
  @java.lang.Override
  public int getOrderId() {
    return orderId_;
  }

  public static final int ORDERTYPE_FIELD_NUMBER = 2;
  private int orderType_;
  /**
   * <code>optional .poc.protobuf.OrderCreated.OrderType orderType = 2;</code>
   * @return Whether the orderType field is set.
   */
  @java.lang.Override public boolean hasOrderType() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .poc.protobuf.OrderCreated.OrderType orderType = 2;</code>
   * @return The orderType.
   */
  @java.lang.Override public poc.protobuf.protos.OrderCreated.OrderType getOrderType() {
    @SuppressWarnings("deprecation")
    poc.protobuf.protos.OrderCreated.OrderType result = poc.protobuf.protos.OrderCreated.OrderType.valueOf(orderType_);
    return result == null ? poc.protobuf.protos.OrderCreated.OrderType.DIRECT : result;
  }

  public static final int CUSTOMERID_FIELD_NUMBER = 3;
  private int customerId_;
  /**
   * <code>optional int32 customerId = 3;</code>
   * @return Whether the customerId field is set.
   */
  @java.lang.Override
  public boolean hasCustomerId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 customerId = 3;</code>
   * @return The customerId.
   */
  @java.lang.Override
  public int getCustomerId() {
    return customerId_;
  }

  public static final int PRODUCTID_FIELD_NUMBER = 4;
  private int productId_;
  /**
   * <code>optional int32 productId = 4;</code>
   * @return Whether the productId field is set.
   */
  @java.lang.Override
  public boolean hasProductId() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int32 productId = 4;</code>
   * @return The productId.
   */
  @java.lang.Override
  public int getProductId() {
    return productId_;
  }

  public static final int QUANTITY_FIELD_NUMBER = 5;
  private int quantity_;
  /**
   * <code>optional int32 quantity = 5;</code>
   * @return Whether the quantity field is set.
   */
  @java.lang.Override
  public boolean hasQuantity() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 quantity = 5;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, orderId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(2, orderType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, customerId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(4, productId_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(5, quantity_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, orderId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, orderType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, customerId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, productId_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, quantity_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof poc.protobuf.protos.OrderCreated)) {
      return super.equals(obj);
    }
    poc.protobuf.protos.OrderCreated other = (poc.protobuf.protos.OrderCreated) obj;

    if (hasOrderId() != other.hasOrderId()) return false;
    if (hasOrderId()) {
      if (getOrderId()
          != other.getOrderId()) return false;
    }
    if (hasOrderType() != other.hasOrderType()) return false;
    if (hasOrderType()) {
      if (orderType_ != other.orderType_) return false;
    }
    if (hasCustomerId() != other.hasCustomerId()) return false;
    if (hasCustomerId()) {
      if (getCustomerId()
          != other.getCustomerId()) return false;
    }
    if (hasProductId() != other.hasProductId()) return false;
    if (hasProductId()) {
      if (getProductId()
          != other.getProductId()) return false;
    }
    if (hasQuantity() != other.hasQuantity()) return false;
    if (hasQuantity()) {
      if (getQuantity()
          != other.getQuantity()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOrderId()) {
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId();
    }
    if (hasOrderType()) {
      hash = (37 * hash) + ORDERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + orderType_;
    }
    if (hasCustomerId()) {
      hash = (37 * hash) + CUSTOMERID_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerId();
    }
    if (hasProductId()) {
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + getProductId();
    }
    if (hasQuantity()) {
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static poc.protobuf.protos.OrderCreated parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static poc.protobuf.protos.OrderCreated parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static poc.protobuf.protos.OrderCreated parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static poc.protobuf.protos.OrderCreated parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static poc.protobuf.protos.OrderCreated parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static poc.protobuf.protos.OrderCreated parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static poc.protobuf.protos.OrderCreated parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static poc.protobuf.protos.OrderCreated parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static poc.protobuf.protos.OrderCreated parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static poc.protobuf.protos.OrderCreated parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static poc.protobuf.protos.OrderCreated parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static poc.protobuf.protos.OrderCreated parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(poc.protobuf.protos.OrderCreated prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code poc.protobuf.OrderCreated}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:poc.protobuf.OrderCreated)
      poc.protobuf.protos.OrderCreatedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return poc.protobuf.protos.OrderCreatedProtos.internal_static_poc_protobuf_OrderCreated_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return poc.protobuf.protos.OrderCreatedProtos.internal_static_poc_protobuf_OrderCreated_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              poc.protobuf.protos.OrderCreated.class, poc.protobuf.protos.OrderCreated.Builder.class);
    }

    // Construct using poc.protobuf.protos.OrderCreated.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      orderId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      orderType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      customerId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      productId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      quantity_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return poc.protobuf.protos.OrderCreatedProtos.internal_static_poc_protobuf_OrderCreated_descriptor;
    }

    @java.lang.Override
    public poc.protobuf.protos.OrderCreated getDefaultInstanceForType() {
      return poc.protobuf.protos.OrderCreated.getDefaultInstance();
    }

    @java.lang.Override
    public poc.protobuf.protos.OrderCreated build() {
      poc.protobuf.protos.OrderCreated result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public poc.protobuf.protos.OrderCreated buildPartial() {
      poc.protobuf.protos.OrderCreated result = new poc.protobuf.protos.OrderCreated(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.orderId_ = orderId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.orderType_ = orderType_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.customerId_ = customerId_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.productId_ = productId_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.quantity_ = quantity_;
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof poc.protobuf.protos.OrderCreated) {
        return mergeFrom((poc.protobuf.protos.OrderCreated)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(poc.protobuf.protos.OrderCreated other) {
      if (other == poc.protobuf.protos.OrderCreated.getDefaultInstance()) return this;
      if (other.hasOrderId()) {
        setOrderId(other.getOrderId());
      }
      if (other.hasOrderType()) {
        setOrderType(other.getOrderType());
      }
      if (other.hasCustomerId()) {
        setCustomerId(other.getCustomerId());
      }
      if (other.hasProductId()) {
        setProductId(other.getProductId());
      }
      if (other.hasQuantity()) {
        setQuantity(other.getQuantity());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              orderId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              int tmpRaw = input.readEnum();
              poc.protobuf.protos.OrderCreated.OrderType tmpValue =
                  poc.protobuf.protos.OrderCreated.OrderType.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(2, tmpRaw);
              } else {
                orderType_ = tmpRaw;
                bitField0_ |= 0x00000002;
              }
              break;
            } // case 16
            case 24: {
              customerId_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              productId_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              quantity_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int orderId_ ;
    /**
     * <code>optional int32 orderId = 1;</code>
     * @return Whether the orderId field is set.
     */
    @java.lang.Override
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 orderId = 1;</code>
     * @return The orderId.
     */
    @java.lang.Override
    public int getOrderId() {
      return orderId_;
    }
    /**
     * <code>optional int32 orderId = 1;</code>
     * @param value The orderId to set.
     * @return This builder for chaining.
     */
    public Builder setOrderId(int value) {
      bitField0_ |= 0x00000001;
      orderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 orderId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      orderId_ = 0;
      onChanged();
      return this;
    }

    private int orderType_ = 0;
    /**
     * <code>optional .poc.protobuf.OrderCreated.OrderType orderType = 2;</code>
     * @return Whether the orderType field is set.
     */
    @java.lang.Override public boolean hasOrderType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .poc.protobuf.OrderCreated.OrderType orderType = 2;</code>
     * @return The orderType.
     */
    @java.lang.Override
    public poc.protobuf.protos.OrderCreated.OrderType getOrderType() {
      @SuppressWarnings("deprecation")
      poc.protobuf.protos.OrderCreated.OrderType result = poc.protobuf.protos.OrderCreated.OrderType.valueOf(orderType_);
      return result == null ? poc.protobuf.protos.OrderCreated.OrderType.DIRECT : result;
    }
    /**
     * <code>optional .poc.protobuf.OrderCreated.OrderType orderType = 2;</code>
     * @param value The orderType to set.
     * @return This builder for chaining.
     */
    public Builder setOrderType(poc.protobuf.protos.OrderCreated.OrderType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      orderType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .poc.protobuf.OrderCreated.OrderType orderType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      orderType_ = 0;
      onChanged();
      return this;
    }

    private int customerId_ ;
    /**
     * <code>optional int32 customerId = 3;</code>
     * @return Whether the customerId field is set.
     */
    @java.lang.Override
    public boolean hasCustomerId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 customerId = 3;</code>
     * @return The customerId.
     */
    @java.lang.Override
    public int getCustomerId() {
      return customerId_;
    }
    /**
     * <code>optional int32 customerId = 3;</code>
     * @param value The customerId to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerId(int value) {
      bitField0_ |= 0x00000004;
      customerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 customerId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      customerId_ = 0;
      onChanged();
      return this;
    }

    private int productId_ ;
    /**
     * <code>optional int32 productId = 4;</code>
     * @return Whether the productId field is set.
     */
    @java.lang.Override
    public boolean hasProductId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 productId = 4;</code>
     * @return The productId.
     */
    @java.lang.Override
    public int getProductId() {
      return productId_;
    }
    /**
     * <code>optional int32 productId = 4;</code>
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(int value) {
      bitField0_ |= 0x00000008;
      productId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 productId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      productId_ = 0;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <code>optional int32 quantity = 5;</code>
     * @return Whether the quantity field is set.
     */
    @java.lang.Override
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 quantity = 5;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>optional int32 quantity = 5;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {
      bitField0_ |= 0x00000010;
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 quantity = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000010);
      quantity_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:poc.protobuf.OrderCreated)
  }

  // @@protoc_insertion_point(class_scope:poc.protobuf.OrderCreated)
  private static final poc.protobuf.protos.OrderCreated DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new poc.protobuf.protos.OrderCreated();
  }

  public static poc.protobuf.protos.OrderCreated getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<OrderCreated>
      PARSER = new com.google.protobuf.AbstractParser<OrderCreated>() {
    @java.lang.Override
    public OrderCreated parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OrderCreated> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderCreated> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public poc.protobuf.protos.OrderCreated getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

