// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderstatus.proto

package poc.protobuf.protos;

public interface OrderStatusUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:poc.protobuf.OrderStatusUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 orderId = 1;</code>
   * @return Whether the orderId field is set.
   */
  boolean hasOrderId();
  /**
   * <code>optional int32 orderId = 1;</code>
   * @return The orderId.
   */
  int getOrderId();

  /**
   * <code>optional .poc.protobuf.OrderStatusUpdate.OrderStatus orderStatus = 2;</code>
   * @return Whether the orderStatus field is set.
   */
  boolean hasOrderStatus();
  /**
   * <code>optional .poc.protobuf.OrderStatusUpdate.OrderStatus orderStatus = 2;</code>
   * @return The orderStatus.
   */
  poc.protobuf.protos.OrderStatusUpdate.OrderStatus getOrderStatus();
}
